printer:
  columns: 48          # 打印宽度（列数）
  encoding: "gb18030"  # 字符编码（utf-8 / gb18030）

receipt:
  store_name: "文艺派串串香重庆火锅"       # 店名称
  start_time: "2026-05-07 09:00:00"      # 开始时间
  end_time: "2026-05-08 09:00:00"        # 结束时间
  market_type: "人民币"                   # 市别
  area: "大厅"                            # 消费区域
  status: "已结"                          # 状态
  print_person: "吧台收银"                # 打印人
  print_time: "2026-05-08 15:33:50"      # 打印时间
  turnover: 10350.40                      # 营业额
  item_consumption: 10350.40              # 品项消费
  service_fee: 0.00                       # 服务费
  min_consumption_fill: 0.00              # 最低消费补齐
  discount_total: 664.64                  # 优惠金额
  member_discount: 0.00                   # 会员价优惠
  promotion_discount: 0.00                # 促销优惠
  gift_discount: 0.00                     # 赠送优惠
  discount_amount: 0.00                   # 折扣金额
  fixed_discount: 154.60                  # 定额优惠
  rounding: 0.00                          # 抹零金额
  revenue: 510.04                         # 营业收入
  wechat_pay: 4568.10                     # 微信支付
  alipay_subsidy: 0.30                    # 支付宝补贴
  cash: 640.00                            # 人民币
  alipay: 703.80                          # 支付宝支付
  meituan_group: 3670.00                  # 美团点评团购
  meituan_waimai: 103.56                  # 美团外卖

  bill_count: 73.00                       # 账单数
  open_table_count: 71.00                 # 开台数
  guest_flow: 159.00                      # 客流量
  avg_bill: 141.79                        # 单均消费
  avg_table: 142.74                       # 桌均消费
  avg_person: 63.74                       # 人均消费
  avg_dining_time: 66.17                  # 平均用餐时间
