printer:
  columns: 48
  encoding: "gb18030"

receipt:
  # 店名称
  store_name: "文艺派串串香重庆火锅"
  # 开始时间
  start_time: "2026-05-07 09:00:00"
  # 结束时间
  end_time: "2026-05-08 09:00:00"
  # 市别
  market_type: "人民币"
  # 消费区域
  area: "大厅"
  # 状态
  status: "已结"
  # 打印人
  print_person: "吧台收银"
  # 打印时间
  print_time: "2026-05-08 15:33:50"
  # 服务费
  service_fee: 0.00
  # 最低消费补齐
  min_consumption_fill: 0.00
  # 优惠金额
  discount_total: 12
  # 会员价优惠
  member_discount: 0.00
  # 促销优惠
  promotion_discount: 0.00
  # 赠送优惠
  gift_discount: 0.00
  # 折扣金额
  discount_amount: 0.00
  # 定额优惠
  fixed_discount: 154.60
  # 抹零金额
  rounding: 0.00
  # 微信支付
  wechat_pay: 6000.00
  # 支付宝补贴
  alipay_subsidy: 0.30
  # 人民币
  cash: 200.00
  # 支付宝支付
  alipay: 1500.00
  # 美团点评团购
  meituan_group: 3670.00
  # 美团外卖
  meituan_waimai: 103.56

  # 账单数
  bill_count: 73.00
  # 开台数
  open_table_count: 71.00
  # 客流量
  guest_flow: 159.00
  # 平均用餐时间
  avg_dining_time: 66.17
